# Generated by Django 5.2 on 2025-06-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_fixedtask_fixedtaskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedtask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
